-- MySQL Script generated by MySQL Workbench
-- Tue Jul 22 15:15:51 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema weber
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema weber
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `weber` DEFAULT CHARACTER SET utf8mb3 ;
USE `weber` ;

-- -----------------------------------------------------
-- Table `weber`.`business`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`business` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  `nit` INT UNSIGNED NOT NULL,
  `status` ENUM('Activo', 'Inactivo') NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nit_UNIQUE` (`nit` ASC) VISIBLE,
  UNIQUE INDEX `idempresa_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `weber`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`categories` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  `description` TEXT NOT NULL,
  `status` ENUM('Activo', 'Inactivo') NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `weber`.`departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`departments` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(90) NOT NULL,
  `region` ENUM('Caribe', 'Centro Oriente', 'Centro Sur', 'Eje Cafetero - Antioquia', 'Llano', 'Pacífico') NOT NULL,
  `status` ENUM('Activo', 'Inactivo') NOT NULL DEFAULT 'Activo',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `departamentos_nombre_unique` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 100
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `weber`.`failed_jobs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`failed_jobs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(255) NOT NULL,
  `connection` TEXT NOT NULL,
  `queue` TEXT NOT NULL,
  `payload` LONGTEXT NOT NULL,
  `exception` LONGTEXT NOT NULL,
  `failed_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `failed_jobs_uuid_unique` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `weber`.`menus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`menus` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `parent_id` INT UNSIGNED NULL DEFAULT NULL,
  `title` VARCHAR(150) NOT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `model` VARCHAR(60) NULL DEFAULT NULL,
  `route` VARCHAR(150) NULL DEFAULT NULL,
  `order` SMALLINT UNSIGNED NOT NULL,
  `icon` VARCHAR(45) NULL DEFAULT NULL,
  `enabled` TINYINT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `weber`.`migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`migrations` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `migration` VARCHAR(255) NOT NULL,
  `batch` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `weber`.`password_resets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`password_resets` (
  `email` VARCHAR(255) NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `password_resets_email_index` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `weber`.`personal_access_tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`personal_access_tokens` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tokenable_type` VARCHAR(255) NOT NULL,
  `tokenable_id` BIGINT UNSIGNED NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `token` VARCHAR(64) NOT NULL,
  `abilities` TEXT NULL DEFAULT NULL,
  `last_used_at` TIMESTAMP NULL DEFAULT NULL,
  `expires_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `personal_access_tokens_token_unique` (`token` ASC) VISIBLE,
  INDEX `personal_access_tokens_tokenable_index` (`tokenable_type` ASC, `tokenable_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `weber`.`pictures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`pictures` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `route` VARCHAR(120) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `weber`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`products` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `price` DECIMAL(12,2) NOT NULL,
  `gain_percentage` FLOAT UNSIGNED NOT NULL,
  `stock` MEDIUMINT UNSIGNED NOT NULL,
  `status` ENUM('Activo', 'Inactivo') NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `weber`.`product_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`product_category` (
  `product_id` INT UNSIGNED NOT NULL,
  `category_id` INT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`product_id`, `category_id`),
  INDEX `fk_productos_has_categorias_productos1_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_productos_has_categorias_categorias1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_productos_has_categorias_categorias1`
    FOREIGN KEY (`category_id`)
    REFERENCES `weber`.`categories` (`id`),
  CONSTRAINT `fk_productos_has_categorias_productos1`
    FOREIGN KEY (`product_id`)
    REFERENCES `weber`.`products` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `weber`.`product_picture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`product_picture` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `picture_id` INT UNSIGNED NOT NULL,
  `product_id` INT UNSIGNED NOT NULL,
  `status` ENUM('Activo', 'Inactivo') NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_productos_has_fotos_fotos1_idx` (`picture_id` ASC) VISIBLE,
  INDEX `fk_productos_has_fotos_productos1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_productos_has_fotos_fotos1`
    FOREIGN KEY (`picture_id`)
    REFERENCES `weber`.`pictures` (`id`),
  CONSTRAINT `fk_productos_has_fotos_productos1`
    FOREIGN KEY (`product_id`)
    REFERENCES `weber`.`products` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `weber`.`towns`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`towns` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(90) COLLATE 'utf8mb3_bin' NOT NULL,
  `department_id` BIGINT UNSIGNED NOT NULL,
  `shortened` VARCHAR(40) COLLATE 'utf8mb3_bin' NULL DEFAULT NULL,
  `status` ENUM('Activo', 'Inactivo') COLLATE 'utf8mb3_bin' NOT NULL DEFAULT 'Activo',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `municipios_nombre_index` (`name` ASC) VISIBLE,
  INDEX `municipios_departamento_id_index` (`department_id` ASC) VISIBLE,
  CONSTRAINT `municipios_departamento_id_foreign`
    FOREIGN KEY (`department_id`)
    REFERENCES `weber`.`departments` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 99774;


-- -----------------------------------------------------
-- Table `weber`.`subsidiary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`subsidiary` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `busine_id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(80) NOT NULL,
  `administrator_id` INT UNSIGNED NOT NULL,
  `direction` VARCHAR(80) NOT NULL,
  `town_id` BIGINT UNSIGNED NOT NULL,
  `phone` BIGINT UNSIGNED NOT NULL,
  `type` ENUM('Principal', 'Subsede') NOT NULL,
  `status` ENUM('Activo', 'Inactivo') NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sucursal_usuarios1_idx` (`administrator_id` ASC) VISIBLE,
  INDEX `fk_sucursal_municipios1_idx` (`town_id` ASC) VISIBLE,
  INDEX `fk_sucursal_empresa1_idx` (`busine_id` ASC) VISIBLE,
  CONSTRAINT `fk_sucursal_empresa1`
    FOREIGN KEY (`busine_id`)
    REFERENCES `weber`.`business` (`id`),
  CONSTRAINT `fk_sucursal_municipios1`
    FOREIGN KEY (`town_id`)
    REFERENCES `weber`.`towns` (`id`),
  CONSTRAINT `fk_sucursal_usuarios1`
    FOREIGN KEY (`administrator_id`)
    REFERENCES `weber`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `weber`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `last_name` VARCHAR(60) NOT NULL,
  `email` VARCHAR(90) NOT NULL,
  `email_verified_at` TIMESTAMP NULL DEFAULT NULL,
  `password` VARCHAR(256) NULL DEFAULT NULL,
  `photo` VARCHAR(45) NULL DEFAULT NULL,
  `gender` VARCHAR(45) NULL DEFAULT NULL,
  `document_type` ENUM('C.C', 'C.E', 'T.I', 'R.C', 'Pasaporte') NOT NULL,
  `document` BIGINT UNSIGNED NOT NULL,
  `phone` BIGINT UNSIGNED NOT NULL,
  `address` VARCHAR(70) NOT NULL,
  `town_id` BIGINT UNSIGNED NOT NULL,
  `birth_date` DATE NOT NULL,
  `role` ENUM('Administrador', 'Empleado', 'Cliente', 'Proveedor') NOT NULL,
  `subsidiary_id` INT UNSIGNED NOT NULL,
  `status` ENUM('Activo', 'Inactivo') NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `remember_token` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `documento_UNIQUE` (`document` ASC) VISIBLE,
  INDEX `fk_usuarios_municipios1_idx` (`town_id` ASC) VISIBLE,
  INDEX `fk_usuarios_sucursal1_idx` (`subsidiary_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_municipios1`
    FOREIGN KEY (`town_id`)
    REFERENCES `weber`.`towns` (`id`),
  CONSTRAINT `fk_usuarios_sucursal1`
    FOREIGN KEY (`subsidiary_id`)
    REFERENCES `weber`.`subsidiary` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `weber`.`purchases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`purchases` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(244) NOT NULL,
  `supplier_id` INT UNSIGNED NOT NULL COMMENT 'ID del proveedor',
  `employee_id` INT UNSIGNED NOT NULL COMMENT 'ID del empleado que procesa la compra',
  `date` DATETIME NOT NULL,
  `amount` DECIMAL(12,2) NOT NULL,
  `status` ENUM('En progreso', 'Cancelada', 'Finalizada') NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_purchases_supplier_idx` (`supplier_id` ASC) VISIBLE,
  INDEX `fk_purchases_employee_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_purchases_employee`
    FOREIGN KEY (`employee_id`)
    REFERENCES `weber`.`users` (`id`),
  CONSTRAINT `fk_purchases_supplier`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `weber`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 94
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `weber`.`purchase_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`purchase_details` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `purchase_id` INT UNSIGNED NOT NULL,
  `product_id` INT UNSIGNED NOT NULL,
  `batch` INT UNSIGNED NULL DEFAULT NULL,
  `expiration_date` DATE NULL DEFAULT NULL,
  `amount` INT UNSIGNED NOT NULL,
  `price` DECIMAL(12,2) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_purchase_details_purchases_idx` (`purchase_id` ASC) VISIBLE,
  INDEX `fk_purchase_details_products_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_purchase_details_products`
    FOREIGN KEY (`product_id`)
    REFERENCES `weber`.`products` (`id`),
  CONSTRAINT `fk_purchase_details_purchases`
    FOREIGN KEY (`purchase_id`)
    REFERENCES `weber`.`purchases` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 155
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `weber`.`sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`sales` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(244) NOT NULL,
  `customer_id` INT UNSIGNED NOT NULL COMMENT 'ID del cliente',
  `employee_id` INT UNSIGNED NOT NULL COMMENT 'ID del empleado que procesa la venta',
  `date` DATETIME NOT NULL,
  `amount` DECIMAL(12,2) NOT NULL,
  `status` ENUM('En progreso', 'Cancelada', 'Finalizada') NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sales_customer_idx` (`customer_id` ASC) VISIBLE,
  INDEX `fk_sales_employee_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_sales_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `weber`.`users` (`id`),
  CONSTRAINT `fk_sales_employee`
    FOREIGN KEY (`employee_id`)
    REFERENCES `weber`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 94
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `weber`.`sale_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`sale_details` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sale_id` INT UNSIGNED NOT NULL,
  `purchase_detail_id` INT UNSIGNED NOT NULL,
  `amount` INT UNSIGNED NOT NULL,
  `price` DECIMAL(12,2) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sale_details_sales_idx` (`sale_id` ASC) VISIBLE,
  INDEX `fk_sale_details_purchase_details_idx` (`purchase_detail_id` ASC) VISIBLE,
  CONSTRAINT `fk_sale_details_purchase_details`
    FOREIGN KEY (`purchase_detail_id`)
    REFERENCES `weber`.`purchase_details` (`id`),
  CONSTRAINT `fk_sale_details_sales`
    FOREIGN KEY (`sale_id`)
    REFERENCES `weber`.`sales` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `weber`.`returns`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`returns` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `observations` TEXT NOT NULL,
  `employee_id` INT UNSIGNED NOT NULL,
  `amount` DECIMAL(12,2) NOT NULL,
  `sale_detail_id` INT UNSIGNED NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_devoluciones_usuarios1_idx` (`employee_id` ASC) VISIBLE,
  INDEX `fk_devoluciones_detalle_venta1_idx` (`sale_detail_id` ASC) VISIBLE,
  CONSTRAINT `fk_devoluciones_detalle_venta1`
    FOREIGN KEY (`sale_detail_id`)
    REFERENCES `weber`.`sale_details` (`id`),
  CONSTRAINT `fk_devoluciones_usuarios1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `weber`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
