-- MySQL Script generated by MySQL Workbench
-- Wed Jul 23 17:18:19 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema weber
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema weber
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `weber` DEFAULT CHARACTER SET utf8mb3 ;
USE `weber` ;

-- -----------------------------------------------------
-- Table `weber`.`archivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`archivos` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `model` VARCHAR(60) NOT NULL,
  `model_id` VARCHAR(45) NOT NULL,
  `uuid` CHAR(36) NOT NULL COMMENT 'UUID único para el archivo',
  `nombre_original` VARCHAR(255) NOT NULL COMMENT 'Nombre original del archivo',
  `ruta_archivo` VARCHAR(500) NOT NULL COMMENT 'Ruta completa en el storage - REDUCIDA',
  `tipo_archivo` ENUM('imagen', 'documento', 'video', 'audio', 'archivo', 'otro') NOT NULL,
  `etiquetas` JSON NULL DEFAULT NULL COMMENT 'Tags adicionales para búsqueda',
  `estado` ENUM('activo', 'archivado', 'eliminado') NULL DEFAULT 'activo',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_unique` (`uuid` ASC) VISIBLE,
  INDEX `tipo_archivo_idx` (`tipo_archivo` ASC) VISIBLE,
  INDEX `estado_idx` (`estado` ASC) VISIBLE,
  INDEX `ruta_archivo_idx` (`ruta_archivo`(100) ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `weber`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`categorias` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `categoria_padre_id` BIGINT UNSIGNED NULL DEFAULT NULL COMMENT 'Para categorías jerárquicas',
  `estado` ENUM('Activo', 'Inactivo') NOT NULL DEFAULT 'Activo',
  PRIMARY KEY (`id`),
  INDEX `fk_categorias_padre_idx` (`categoria_padre_id` ASC) VISIBLE,
  CONSTRAINT `fk_categorias_padre`
    FOREIGN KEY (`categoria_padre_id`)
    REFERENCES `weber`.`categorias` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `weber`.`departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`departamentos` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(90) NOT NULL,
  `region` ENUM('Caribe', 'Centro Oriente', 'Centro Sur', 'Eje Cafetero - Antioquia', 'Llano', 'Pacífico') NOT NULL,
  `estado` ENUM('Activo', 'Inactivo') NOT NULL DEFAULT 'Activo',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `departamentos_nombre_unique` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 100
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `weber`.`municipios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`municipios` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(90) NOT NULL,
  `departamento_id` BIGINT UNSIGNED NOT NULL,
  `abreviatura` VARCHAR(40) NULL DEFAULT NULL,
  `estado` ENUM('Activo', 'Inactivo') NOT NULL DEFAULT 'Activo',
  PRIMARY KEY (`id`),
  INDEX `municipios_nombre_index` (`nombre` ASC) VISIBLE,
  INDEX `municipios_departamento_id_index` (`departamento_id` ASC) VISIBLE,
  CONSTRAINT `municipios_departamento_id_foreign`
    FOREIGN KEY (`departamento_id`)
    REFERENCES `weber`.`departamentos` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 99774
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `weber`.`empresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`empresas` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NOT NULL,
  `nit` VARCHAR(20) NOT NULL COMMENT 'Número de Identificación Tributaria',
  `estado` ENUM('Activo', 'Inactivo') NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nit_UNIQUE` (`nit` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `weber`.`sucursales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`sucursales` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `empresa_id` BIGINT UNSIGNED NOT NULL,
  `nombre` VARCHAR(80) NOT NULL,
  `administrador_id` BIGINT UNSIGNED NOT NULL COMMENT 'Referencia a perfiles_usuario',
  `direccion` VARCHAR(200) NOT NULL,
  `municipio_id` BIGINT UNSIGNED NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `tipo` ENUM('Principal', 'Subsede') NOT NULL,
  `estado` ENUM('Activo', 'Inactivo') NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sucursales_administrador_idx` (`administrador_id` ASC) VISIBLE,
  INDEX `fk_sucursales_municipios_idx` (`municipio_id` ASC) VISIBLE,
  INDEX `fk_sucursales_empresas_idx` (`empresa_id` ASC) VISIBLE,
  CONSTRAINT `fk_sucursales_administrador`
    FOREIGN KEY (`administrador_id`)
    REFERENCES `weber`.`perfiles_usuario` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_sucursales_empresas`
    FOREIGN KEY (`empresa_id`)
    REFERENCES `weber`.`empresas` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_sucursales_municipios`
    FOREIGN KEY (`municipio_id`)
    REFERENCES `weber`.`municipios` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `weber`.`perfiles_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`perfiles_usuario` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `usuario_id` BIGINT UNSIGNED NOT NULL COMMENT 'ID del usuario en la tabla del framework (users de Laravel/Django)',
  `codigo_empleado` VARCHAR(20) NULL DEFAULT NULL COMMENT 'Código de empleado interno',
  `tipo_documento` ENUM('C.C', 'C.E', 'T.I', 'R.C', 'Pasaporte') NOT NULL,
  `documento` VARCHAR(20) NOT NULL COMMENT 'Número de documento de identidad',
  `telefono` VARCHAR(20) NULL DEFAULT NULL COMMENT 'Teléfono de contacto',
  `direccion` VARCHAR(200) NULL DEFAULT NULL,
  `municipio_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `fecha_nacimiento` DATE NULL DEFAULT NULL,
  `rol_negocio` ENUM('Administrador', 'Empleado', 'Cliente', 'Proveedor') NOT NULL,
  `sucursal_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `estado` ENUM('Activo', 'Inactivo', 'Suspendido') NOT NULL DEFAULT 'Activo',
  `fecha_contratacion` DATE NULL DEFAULT NULL COMMENT 'Fecha de contratación para empleados',
  `fecha_terminacion` DATE NULL DEFAULT NULL COMMENT 'Fecha de terminación',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `documento_unique` (`documento` ASC) VISIBLE,
  UNIQUE INDEX `usuario_framework_unique` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_perfiles_usuario_municipios_idx` (`municipio_id` ASC) VISIBLE,
  INDEX `fk_perfiles_usuario_sucursal_idx` (`sucursal_id` ASC) VISIBLE,
  INDEX `rol_negocio_idx` (`rol_negocio` ASC) VISIBLE,
  CONSTRAINT `fk_perfiles_usuario_municipios`
    FOREIGN KEY (`municipio_id`)
    REFERENCES `weber`.`municipios` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_perfiles_usuario_sucursal`
    FOREIGN KEY (`sucursal_id`)
    REFERENCES `weber`.`sucursales` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `weber`.`transacciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`transacciones` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(50) NOT NULL,
  `perfil_usuario_id` BIGINT UNSIGNED NOT NULL COMMENT 'Cliente/Proveedor desde perfiles_usuario',
  `perfil_empleado_id` BIGINT UNSIGNED NOT NULL COMMENT 'Empleado desde perfiles_usuario',
  `fecha` DATETIME NOT NULL,
  `monto` DECIMAL(15,2) NOT NULL,
  `estado` ENUM('En progreso', 'Cancelada', 'Finalizada') NOT NULL,
  `observaciones` TEXT NULL DEFAULT NULL COMMENT 'Notas adicionales',
  `fecha_creacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `fecha_eliminacion` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `numero_unique` (`numero` ASC) VISIBLE,
  INDEX `fk_transacciones_perfil_usuario_idx` (`perfil_usuario_id` ASC) VISIBLE,
  INDEX `fk_transacciones_perfil_empleado_idx` (`perfil_empleado_id` ASC) VISIBLE,
  INDEX `fecha_idx` (`fecha` ASC) VISIBLE,
  INDEX `estado_idx` (`estado` ASC) VISIBLE,
  CONSTRAINT `fk_transacciones_perfil_empleado`
    FOREIGN KEY (`perfil_empleado_id`)
    REFERENCES `weber`.`perfiles_usuario` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_transacciones_perfil_usuario`
    FOREIGN KEY (`perfil_usuario_id`)
    REFERENCES `weber`.`perfiles_usuario` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `weber`.`compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`compras` (
  `id` BIGINT UNSIGNED NOT NULL,
  `perfil_proveedor_id` BIGINT UNSIGNED NOT NULL COMMENT 'Referencia específica al proveedor',
  `fecha_entrega` DATE NULL DEFAULT NULL,
  `numero_factura_proveedor` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Número de factura del proveedor',
  `terminos_pago` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Términos de pago',
  `direccion_entrega` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_compras_perfil_proveedor_idx` (`perfil_proveedor_id` ASC) VISIBLE,
  CONSTRAINT `fk_compras_perfil_proveedor`
    FOREIGN KEY (`perfil_proveedor_id`)
    REFERENCES `weber`.`perfiles_usuario` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_compras_transacciones`
    FOREIGN KEY (`id`)
    REFERENCES `weber`.`transacciones` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `weber`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`productos` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(50) NULL DEFAULT NULL COMMENT 'Código único del producto (SKU)',
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `stock` INT UNSIGNED NOT NULL DEFAULT '0',
  `stock_minimo` INT UNSIGNED NULL DEFAULT '0' COMMENT 'Stock mínimo para alertas',
  `stock_maximo` INT UNSIGNED NULL DEFAULT NULL COMMENT 'Stock máximo',
  `unidad` VARCHAR(20) NULL DEFAULT 'Unidad' COMMENT 'Unidad de medida',
  `ganancia_sugerido` DECIMAL(5,2) NULL DEFAULT '50.00' COMMENT 'Porcentaje de ganancia sugerido (puede cambiar)',
  `estado` ENUM('Activo', 'Inactivo', 'Descontinuado') NOT NULL DEFAULT 'Activo',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `codigo_unique` (`codigo` ASC) VISIBLE,
  INDEX `nombre_idx` (`nombre` ASC) VISIBLE,
  INDEX `estado_idx` (`estado` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `weber`.`detalles_compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`detalles_compras` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `compra_id` BIGINT UNSIGNED NOT NULL,
  `producto_id` BIGINT UNSIGNED NOT NULL,
  `lote` VARCHAR(50) NULL DEFAULT NULL COMMENT 'Número de lote (opcional)',
  `fecha_vencimiento` DATE NULL DEFAULT NULL,
  `cantidad` DECIMAL(10,2) NOT NULL,
  `costo_unitario` DECIMAL(15,2) NOT NULL,
  `subtotal` DECIMAL(15,2) NOT NULL,
  `monto_impuesto` DECIMAL(15,2) NULL DEFAULT '0.00',
  `cantidad_disponible` DECIMAL(10,2) NOT NULL COMMENT 'Cantidad disponible para venta (se reduce con cada venta)',
  `porcentaje_ganancia_aplicado` DECIMAL(5,2) NOT NULL COMMENT 'Porcentaje de ganancia aplicado a este lote',
  `precio_venta_calculado` DECIMAL(15,2) NOT NULL COMMENT 'Precio de venta calculado con la ganancia',
  `esta_agotado` TINYINT(1) NULL DEFAULT '0' COMMENT 'TRUE cuando cantidad_disponible = 0',
  PRIMARY KEY (`id`),
  INDEX `fk_detalles_compras_compras_idx` (`compra_id` ASC) VISIBLE,
  INDEX `fk_detalles_compras_productos_idx` (`producto_id` ASC) VISIBLE,
  INDEX `lote_idx` (`lote` ASC) VISIBLE,
  INDEX `fecha_vencimiento_idx` (`fecha_vencimiento` ASC) VISIBLE,
  INDEX `cantidad_disponible_idx` (`cantidad_disponible` ASC) VISIBLE,
  INDEX `esta_agotado_idx` (`esta_agotado` ASC) VISIBLE,
  INDEX `fifo_orden_idx` (`producto_id` ASC) COMMENT '\'Índice para ordenamiento FIFO\'' VISIBLE,
  CONSTRAINT `fk_detalles_compras_compras`
    FOREIGN KEY (`compra_id`)
    REFERENCES `weber`.`compras` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_detalles_compras_productos`
    FOREIGN KEY (`producto_id`)
    REFERENCES `weber`.`productos` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `weber`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`ventas` (
  `id` BIGINT UNSIGNED NOT NULL,
  `perfil_cliente_id` BIGINT UNSIGNED NOT NULL COMMENT 'Referencia específica al cliente',
  `metodo_pago` ENUM('Efectivo', 'Tarjeta', 'Transferencia', 'Crédito') NULL DEFAULT 'Efectivo',
  `porcentaje_descuento` DECIMAL(5,2) NULL DEFAULT '0.00',
  `porcentaje_impuesto` DECIMAL(5,2) NULL DEFAULT '0.00',
  `numero_factura` VARCHAR(50) NULL DEFAULT NULL COMMENT 'Número de factura generada',
  PRIMARY KEY (`id`),
  INDEX `fk_ventas_perfil_cliente_idx` (`perfil_cliente_id` ASC) VISIBLE,
  CONSTRAINT `fk_ventas_perfil_cliente`
    FOREIGN KEY (`perfil_cliente_id`)
    REFERENCES `weber`.`perfiles_usuario` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ventas_transacciones`
    FOREIGN KEY (`id`)
    REFERENCES `weber`.`transacciones` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `weber`.`detalles_ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`detalles_ventas` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `venta_id` BIGINT UNSIGNED NOT NULL,
  `producto_id` BIGINT UNSIGNED NOT NULL,
  `cantidad` DECIMAL(10,2) NOT NULL COMMENT 'Permite decimales para productos fraccionables',
  `precio_unitario` DECIMAL(15,2) NOT NULL COMMENT 'Precio de venta por unidad',
  `subtotal` DECIMAL(15,2) NOT NULL,
  `monto_descuento` DECIMAL(15,2) NULL DEFAULT '0.00',
  `monto_impuesto` DECIMAL(15,2) NULL DEFAULT '0.00',
  `costo_unitario_promedio` DECIMAL(15,2) NOT NULL COMMENT 'Costo promedio ponderado al momento de la venta',
  `ganancia_unitaria` DECIMAL(15,2) NOT NULL COMMENT 'Ganancia por unidad (precio_unitario - costo_unitario_promedio)',
  `ganancia_total` DECIMAL(15,2) NOT NULL COMMENT 'Ganancia total del detalle',
  `porcentaje_ganancia_real` DECIMAL(5,2) NOT NULL COMMENT 'Porcentaje de ganancia real obtenido',
  PRIMARY KEY (`id`),
  INDEX `fk_detalles_ventas_ventas_idx` (`venta_id` ASC) VISIBLE,
  INDEX `fk_detalles_ventas_productos_idx` (`producto_id` ASC) VISIBLE,
  INDEX `ganancia_idx` (`ganancia_total` ASC) VISIBLE,
  INDEX `porcentaje_ganancia_idx` (`porcentaje_ganancia_real` ASC) VISIBLE,
  CONSTRAINT `fk_detalles_ventas_productos`
    FOREIGN KEY (`producto_id`)
    REFERENCES `weber`.`productos` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_detalles_ventas_ventas`
    FOREIGN KEY (`venta_id`)
    REFERENCES `weber`.`ventas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `weber`.`devoluciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`devoluciones` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NOT NULL,
  `observaciones` TEXT NOT NULL,
  `perfil_empleado_id` BIGINT UNSIGNED NULL,
  `monto` DECIMAL(15,2) NOT NULL,
  `detalle_venta_id` BIGINT UNSIGNED NULL DEFAULT NULL COMMENT 'Para devoluciones de ventas',
  `detalle_compra_id` BIGINT UNSIGNED NULL DEFAULT NULL COMMENT 'Para devoluciones de compras',
  `tipo_devolucion` ENUM('Venta', 'Compra') NOT NULL,
  `estado` ENUM('Pendiente', 'Procesada', 'Cancelada') NULL DEFAULT 'Pendiente',
  PRIMARY KEY (`id`),
  INDEX `fk_devoluciones_perfil_empleado_idx` (`perfil_empleado_id` ASC) VISIBLE,
  INDEX `fk_devoluciones_detalle_venta_idx` (`detalle_venta_id` ASC) VISIBLE,
  INDEX `fk_devoluciones_detalle_compra_idx` (`detalle_compra_id` ASC) VISIBLE,
  INDEX `tipo_devolucion_idx` (`tipo_devolucion` ASC) VISIBLE,
  CONSTRAINT `fk_devoluciones_detalle_compra`
    FOREIGN KEY (`detalle_compra_id`)
    REFERENCES `weber`.`detalles_compras` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_devoluciones_detalle_venta`
    FOREIGN KEY (`detalle_venta_id`)
    REFERENCES `weber`.`detalles_ventas` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_devoluciones_perfil_empleado`
    FOREIGN KEY (`perfil_empleado_id`)
    REFERENCES `weber`.`perfiles_usuario` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `weber`.`movimientos_inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`movimientos_inventario` (
  `id` BIGINT(19) UNSIGNED NOT NULL AUTO_INCREMENT,
  `producto_id` BIGINT(19) UNSIGNED NOT NULL,
  `tipo_movimiento` ENUM('Entrada', 'Salida', 'Ajuste') NOT NULL,
  `tipo_documento` ENUM('Compra', 'Venta', 'Devolucion', 'Ajuste_Inventario') NOT NULL,
  `documento_id` BIGINT(19) UNSIGNED NOT NULL COMMENT 'ID del documento origen (compra_id, venta_id, etc.)',
  `detalle_documento_id` BIGINT(19) UNSIGNED NULL DEFAULT NULL COMMENT 'ID del detalle específico',
  `cantidad` DECIMAL(10,2) NOT NULL COMMENT 'Cantidad del movimiento (+ para entradas, - para salidas)',
  `costo_unitario` DECIMAL(15,2) NOT NULL COMMENT 'Costo unitario del movimiento',
  `costo_total` DECIMAL(15,2) NOT NULL COMMENT 'Costo total del movimiento',
  `detalle_compra_origen_id` BIGINT(19) UNSIGNED NULL DEFAULT NULL COMMENT 'De qué compra sale este producto (para salidas)',
  `stock_anterior` DECIMAL(10,2) NOT NULL,
  `stock_nuevo` DECIMAL(10,2) NOT NULL,
  `observaciones` TEXT NULL DEFAULT NULL,
  `usuario_perfil_id` BIGINT(19) UNSIGNED NULL DEFAULT NULL COMMENT 'Usuario que realizó el movimiento',
  `fecha_movimiento` DATETIME NOT NULL,
  `fecha_creacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_movimientos_producto_idx` (`producto_id` ASC) VISIBLE,
  INDEX `fk_movimientos_usuario_idx` (`usuario_perfil_id` ASC) VISIBLE,
  INDEX `fk_movimientos_detalle_compra_idx` (`detalle_compra_origen_id` ASC) VISIBLE,
  INDEX `tipo_movimiento_idx` (`tipo_movimiento` ASC) VISIBLE,
  INDEX `tipo_documento_idx` (`tipo_documento` ASC) VISIBLE,
  INDEX `fecha_movimiento_idx` (`fecha_movimiento` ASC) VISIBLE,
  INDEX `documento_idx` (`tipo_documento` ASC, `documento_id` ASC) VISIBLE,
  CONSTRAINT `fk_movimientos_detalle_compra`
    FOREIGN KEY (`detalle_compra_origen_id`)
    REFERENCES `weber`.`detalles_compras` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_movimientos_producto`
    FOREIGN KEY (`producto_id`)
    REFERENCES `weber`.`productos` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_movimientos_usuario`
    FOREIGN KEY (`usuario_perfil_id`)
    REFERENCES `weber`.`perfiles_usuario` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `weber`.`producto_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`producto_categoria` (
  `producto_id` BIGINT UNSIGNED NOT NULL,
  `categoria_id` BIGINT UNSIGNED NOT NULL,
  `fecha_creacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`producto_id`, `categoria_id`),
  INDEX `fk_producto_categoria_productos_idx` (`producto_id` ASC) VISIBLE,
  INDEX `fk_producto_categoria_categorias_idx` (`categoria_id` ASC) VISIBLE,
  CONSTRAINT `fk_producto_categoria_categorias`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `weber`.`categorias` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_producto_categoria_productos`
    FOREIGN KEY (`producto_id`)
    REFERENCES `weber`.`productos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

USE `weber` ;

-- -----------------------------------------------------
-- Placeholder table for view `weber`.`v_adjuntos_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`v_adjuntos_productos` (`id_adjunto` INT, `id_producto` INT, `tipo_adjunto` INT, `titulo` INT, `descripcion` INT, `orden_visualizacion` INT, `es_principal` INT, `estado_adjunto` INT, `id_archivo` INT, `uuid` INT, `nombre_original` INT, `ruta_archivo` INT, `url_publica` INT, `tipo_mime` INT, `tamaño_archivo` INT, `tipo_archivo` INT, `esta_procesado` INT, `nombre_producto` INT, `codigo_producto` INT, `estado_producto` INT);

-- -----------------------------------------------------
-- Placeholder table for view `weber`.`v_archivos_completos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`v_archivos_completos` (`id` INT, `uuid` INT, `nombre_original` INT, `nombre_almacenado` INT, `ruta_archivo` INT, `url_publica` INT, `tipo_mime` INT, `extension_archivo` INT, `tamaño_archivo` INT, `tipo_archivo` INT, `categoria` INT, `esta_procesado` INT, `estado_procesamiento` INT, `es_publico` INT, `nivel_acceso` INT, `estado` INT, `fecha_creacion` INT, `fecha_actualizacion` INT, `proveedor_almacenamiento` INT, `nombre_mostrar_almacenamiento` INT, `controlador_almacenamiento` INT, `subido_por_documento` INT, `subido_por_rol` INT);

-- -----------------------------------------------------
-- Placeholder table for view `weber`.`v_disponibilidad_fifo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`v_disponibilidad_fifo` (`producto_id` INT, `codigo` INT, `nombre_producto` INT, `stock_total` INT, `detalle_compra_id` INT, `compra_id` INT, `cantidad_disponible` INT, `costo_unitario` INT, `precio_venta_calculado` INT, `porcentaje_ganancia_aplicado` INT, `lote` INT, `fecha_vencimiento` INT, `fecha_entrada` INT, `dias_para_vencer` INT);

-- -----------------------------------------------------
-- Placeholder table for view `weber`.`v_rentabilidad_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`v_rentabilidad_productos` (`producto_id` INT, `codigo` INT, `nombre_producto` INT, `total_ventas` INT, `cantidad_total_vendida` INT, `ingresos_totales` INT, `costos_totales` INT, `ganancia_total` INT, `porcentaje_ganancia_promedio` INT, `porcentaje_ganancia_minimo` INT, `porcentaje_ganancia_maximo` INT);

-- -----------------------------------------------------
-- Placeholder table for view `weber`.`v_todas_transacciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`v_todas_transacciones` (`id` INT, `numero` INT, `perfil_usuario_id` INT, `perfil_empleado_id` INT, `fecha` INT, `monto` INT, `estado` INT, `tipo_transaccion` INT, `perfil_usuario_relacionado_id` INT, `metodo_pago` INT, `fecha_entrega` INT, `numero_factura` INT);

-- -----------------------------------------------------
-- Placeholder table for view `weber`.`v_usuarios_compatibilidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`v_usuarios_compatibilidad` (`id` INT, `usuario_framework_id` INT, `tipo_framework` INT, `tipo_documento` INT, `documento` INT, `telefono` INT, `direccion` INT, `municipio_id` INT, `fecha_nacimiento` INT, `rol_negocio` INT, `sucursal_id` INT, `estado` INT, `fecha_creacion` INT, `fecha_actualizacion` INT, `fecha_eliminacion` INT);

-- -----------------------------------------------------
-- procedure procesar_fifo_salida
-- -----------------------------------------------------

DELIMITER $$
USE `weber`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `procesar_fifo_salida`(
    IN p_producto_id BIGINT UNSIGNED,
    IN p_cantidad_vendida DECIMAL(10,2),
    IN p_detalle_venta_id BIGINT UNSIGNED
)
BEGIN
    DECLARE cantidad_restante DECIMAL(10,2) DEFAULT p_cantidad_vendida;
    DECLARE done INT DEFAULT FALSE;
    DECLARE lote_id BIGINT UNSIGNED;
    DECLARE cantidad_lote DECIMAL(10,2);
    DECLARE costo_lote DECIMAL(15,2);
    DECLARE cantidad_a_descontar DECIMAL(10,2);

    DECLARE cur_fifo CURSOR FOR
        SELECT id, cantidad_disponible, costo_unitario
        FROM detalles_compras
        WHERE producto_id = p_producto_id 
          AND cantidad_disponible > 0 
          AND esta_agotado = FALSE
        ORDER BY fecha_creacion ASC;

    DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = TRUE;

    OPEN cur_fifo;

    read_loop: LOOP
        FETCH cur_fifo INTO lote_id, cantidad_lote, costo_lote;

        IF done OR cantidad_restante <= 0 THEN
            LEAVE read_loop;
        END IF;

        SET cantidad_a_descontar = LEAST(cantidad_restante, cantidad_lote);

        -- Actualizar cantidad disponible en el lote
        UPDATE detalles_compras 
        SET cantidad_disponible = cantidad_disponible - cantidad_a_descontar,
            esta_agotado = CASE WHEN (cantidad_disponible - cantidad_a_descontar) <= 0 THEN TRUE ELSE FALSE END,
            fecha_actualizacion = NOW()
        WHERE id = lote_id;

        -- Insertar detalle del movimiento FIFO
        INSERT INTO movimientos_inventario (
            producto_id, tipo_movimiento, tipo_documento, documento_id, detalle_documento_id,
            cantidad, costo_unitario, costo_total, detalle_compra_origen_id,
            stock_anterior, stock_nuevo, fecha_movimiento, observaciones
        ) VALUES (
            p_producto_id, 'Salida', 'Venta', 0, p_detalle_venta_id,
            -cantidad_a_descontar, costo_lote, -(cantidad_a_descontar * costo_lote), lote_id,
            0, 0, NOW(), CONCAT('FIFO - Lote ID: ', lote_id)
        );

        SET cantidad_restante = cantidad_restante - cantidad_a_descontar;

    END LOOP;

    CLOSE cur_fifo;

END$$

DELIMITER ;

-- -----------------------------------------------------
-- View `weber`.`v_adjuntos_productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weber`.`v_adjuntos_productos`;
USE `weber`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `weber`.`v_adjuntos_productos` AS select `adj`.`id` AS `id_adjunto`,`adj`.`id_adjuntable` AS `id_producto`,`adj`.`tipo_adjunto` AS `tipo_adjunto`,`adj`.`titulo` AS `titulo`,`adj`.`descripcion` AS `descripcion`,`adj`.`orden_visualizacion` AS `orden_visualizacion`,`adj`.`es_principal` AS `es_principal`,`adj`.`estado` AS `estado_adjunto`,`a`.`id` AS `id_archivo`,`a`.`uuid` AS `uuid`,`a`.`nombre_original` AS `nombre_original`,`a`.`ruta_archivo` AS `ruta_archivo`,`a`.`url_publica` AS `url_publica`,`a`.`tipo_mime` AS `tipo_mime`,`a`.`tamaño_archivo` AS `tamaño_archivo`,`a`.`tipo_archivo` AS `tipo_archivo`,`a`.`esta_procesado` AS `esta_procesado`,`p`.`nombre` AS `nombre_producto`,`p`.`codigo` AS `codigo_producto`,`p`.`estado` AS `estado_producto` from ((`weber`.`adjuntos` `adj` join `weber`.`archivos` `a` on((`adj`.`archivo_id` = `a`.`id`))) join `weber`.`productos` `p` on((`adj`.`id_adjuntable` = `p`.`id`))) where ((`adj`.`tipo_adjuntable` = 'Producto') and (`adj`.`estado` = 'activo') and (`a`.`estado` = 'activo'));

-- -----------------------------------------------------
-- View `weber`.`v_archivos_completos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weber`.`v_archivos_completos`;
USE `weber`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `weber`.`v_archivos_completos` AS select `a`.`id` AS `id`,`a`.`uuid` AS `uuid`,`a`.`nombre_original` AS `nombre_original`,`a`.`nombre_almacenado` AS `nombre_almacenado`,`a`.`ruta_archivo` AS `ruta_archivo`,`a`.`url_publica` AS `url_publica`,`a`.`tipo_mime` AS `tipo_mime`,`a`.`extension_archivo` AS `extension_archivo`,`a`.`tamaño_archivo` AS `tamaño_archivo`,`a`.`tipo_archivo` AS `tipo_archivo`,`a`.`categoria` AS `categoria`,`a`.`esta_procesado` AS `esta_procesado`,`a`.`estado_procesamiento` AS `estado_procesamiento`,`a`.`es_publico` AS `es_publico`,`a`.`nivel_acceso` AS `nivel_acceso`,`a`.`estado` AS `estado`,`a`.`fecha_creacion` AS `fecha_creacion`,`a`.`fecha_actualizacion` AS `fecha_actualizacion`,`pa`.`nombre` AS `proveedor_almacenamiento`,`pa`.`nombre_mostrar` AS `nombre_mostrar_almacenamiento`,`pa`.`controlador` AS `controlador_almacenamiento`,`pu`.`documento` AS `subido_por_documento`,`pu`.`rol_negocio` AS `subido_por_rol` from ((`weber`.`archivos` `a` join `weber`.`proveedores_almacenamiento` `pa` on((`a`.`proveedor_almacenamiento_id` = `pa`.`id`))) left join `weber`.`perfiles_usuario` `pu` on((`a`.`subido_por_perfil_id` = `pu`.`id`)));

-- -----------------------------------------------------
-- View `weber`.`v_disponibilidad_fifo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weber`.`v_disponibilidad_fifo`;
USE `weber`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `weber`.`v_disponibilidad_fifo` AS select `p`.`id` AS `producto_id`,`p`.`codigo` AS `codigo`,`p`.`nombre` AS `nombre_producto`,`p`.`stock` AS `stock_total`,`dc`.`id` AS `detalle_compra_id`,`dc`.`compra_id` AS `compra_id`,`dc`.`cantidad_disponible` AS `cantidad_disponible`,`dc`.`costo_unitario` AS `costo_unitario`,`dc`.`precio_venta_calculado` AS `precio_venta_calculado`,`dc`.`porcentaje_ganancia_aplicado` AS `porcentaje_ganancia_aplicado`,`dc`.`lote` AS `lote`,`dc`.`fecha_vencimiento` AS `fecha_vencimiento`,`dc`.`fecha_creacion` AS `fecha_entrada`,(to_days(`dc`.`fecha_vencimiento`) - to_days(curdate())) AS `dias_para_vencer` from (`weber`.`productos` `p` join `weber`.`detalles_compras` `dc` on((`p`.`id` = `dc`.`producto_id`))) where ((`dc`.`cantidad_disponible` > 0) and (`dc`.`esta_agotado` = false) and (`p`.`estado` = 'Activo')) order by `p`.`id`,`dc`.`fecha_creacion`;

-- -----------------------------------------------------
-- View `weber`.`v_rentabilidad_productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weber`.`v_rentabilidad_productos`;
USE `weber`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `weber`.`v_rentabilidad_productos` AS select `p`.`id` AS `producto_id`,`p`.`codigo` AS `codigo`,`p`.`nombre` AS `nombre_producto`,count(`dv`.`id`) AS `total_ventas`,sum(`dv`.`cantidad`) AS `cantidad_total_vendida`,sum(`dv`.`subtotal`) AS `ingresos_totales`,sum((`dv`.`cantidad` * `dv`.`costo_unitario_promedio`)) AS `costos_totales`,sum(`dv`.`ganancia_total`) AS `ganancia_total`,avg(`dv`.`porcentaje_ganancia_real`) AS `porcentaje_ganancia_promedio`,min(`dv`.`porcentaje_ganancia_real`) AS `porcentaje_ganancia_minimo`,max(`dv`.`porcentaje_ganancia_real`) AS `porcentaje_ganancia_maximo` from (`weber`.`productos` `p` left join `weber`.`detalles_ventas` `dv` on((`p`.`id` = `dv`.`producto_id`))) where (`p`.`estado` = 'Activo') group by `p`.`id`,`p`.`codigo`,`p`.`nombre`;

-- -----------------------------------------------------
-- View `weber`.`v_todas_transacciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weber`.`v_todas_transacciones`;
USE `weber`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `weber`.`v_todas_transacciones` AS select `t`.`id` AS `id`,`t`.`numero` AS `numero`,`t`.`perfil_usuario_id` AS `perfil_usuario_id`,`t`.`perfil_empleado_id` AS `perfil_empleado_id`,`t`.`fecha` AS `fecha`,`t`.`monto` AS `monto`,`t`.`estado` AS `estado`,'Venta' AS `tipo_transaccion`,`v`.`perfil_cliente_id` AS `perfil_usuario_relacionado_id`,`v`.`metodo_pago` AS `metodo_pago`,NULL AS `fecha_entrega`,`v`.`numero_factura` AS `numero_factura` from (`weber`.`transacciones` `t` join `weber`.`ventas` `v` on((`t`.`id` = `v`.`id`))) union all select `t`.`id` AS `id`,`t`.`numero` AS `numero`,`t`.`perfil_usuario_id` AS `perfil_usuario_id`,`t`.`perfil_empleado_id` AS `perfil_empleado_id`,`t`.`fecha` AS `fecha`,`t`.`monto` AS `monto`,`t`.`estado` AS `estado`,'Compra' AS `tipo_transaccion`,`c`.`perfil_proveedor_id` AS `perfil_usuario_relacionado_id`,NULL AS `metodo_pago`,`c`.`fecha_entrega` AS `fecha_entrega`,`c`.`numero_factura_proveedor` AS `numero_factura` from (`weber`.`transacciones` `t` join `weber`.`compras` `c` on((`t`.`id` = `c`.`id`)));

-- -----------------------------------------------------
-- View `weber`.`v_usuarios_compatibilidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weber`.`v_usuarios_compatibilidad`;
USE `weber`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `weber`.`v_usuarios_compatibilidad` AS select `pu`.`id` AS `id`,`pu`.`usuario_framework_id` AS `usuario_framework_id`,`pu`.`tipo_framework` AS `tipo_framework`,`pu`.`tipo_documento` AS `tipo_documento`,`pu`.`documento` AS `documento`,`pu`.`telefono` AS `telefono`,`pu`.`direccion` AS `direccion`,`pu`.`municipio_id` AS `municipio_id`,`pu`.`fecha_nacimiento` AS `fecha_nacimiento`,`pu`.`rol_negocio` AS `rol_negocio`,`pu`.`sucursal_id` AS `sucursal_id`,`pu`.`estado` AS `estado`,`pu`.`fecha_creacion` AS `fecha_creacion`,`pu`.`fecha_actualizacion` AS `fecha_actualizacion`,`pu`.`fecha_eliminacion` AS `fecha_eliminacion` from `weber`.`perfiles_usuario` `pu`;
USE `weber`;

DELIMITER $$
USE `weber`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `weber`.`tr_entrada_inventario_compra`
AFTER INSERT ON `weber`.`detalles_compras`
FOR EACH ROW
BEGIN
    DECLARE stock_actual DECIMAL(10,2) DEFAULT 0;

    -- Obtener stock actual
    SELECT stock INTO stock_actual FROM productos WHERE id = NEW.producto_id;

    -- Insertar movimiento de entrada
    INSERT INTO movimientos_inventario (
        producto_id, tipo_movimiento, tipo_documento, documento_id, detalle_documento_id,
        cantidad, costo_unitario, costo_total, stock_anterior, stock_nuevo, fecha_movimiento
    ) VALUES (
        NEW.producto_id, 'Entrada', 'Compra', NEW.compra_id, NEW.id,
        NEW.cantidad, NEW.costo_unitario, NEW.subtotal, 
        stock_actual, stock_actual + NEW.cantidad, NOW()
    );

    -- Actualizar stock del producto
    UPDATE productos 
    SET stock = stock + NEW.cantidad,
        fecha_actualizacion = NOW()
    WHERE id = NEW.producto_id;
END$$

USE `weber`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `weber`.`tr_salida_inventario_venta`
AFTER INSERT ON `weber`.`detalles_ventas`
FOR EACH ROW
BEGIN
    -- TODAS LAS DECLARACIONES AL INICIO
    DECLARE cantidad_restante DECIMAL(10,2) DEFAULT NEW.cantidad;
    DECLARE stock_actual DECIMAL(10,2) DEFAULT 0;
    DECLARE costo_promedio DECIMAL(15,2) DEFAULT 0;
    DECLARE done INT DEFAULT FALSE;

    -- Variables para el cursor (declaradas al inicio)
    DECLARE lote_id BIGINT UNSIGNED DEFAULT 0;
    DECLARE cantidad_lote DECIMAL(10,2) DEFAULT 0;
    DECLARE costo_lote DECIMAL(15,2) DEFAULT 0;
    DECLARE cantidad_a_descontar DECIMAL(10,2) DEFAULT 0;

    -- Cursor para obtener lotes disponibles en orden FIFO
    DECLARE cur_fifo CURSOR FOR
        SELECT id, cantidad_disponible, costo_unitario
        FROM detalles_compras
        WHERE producto_id = NEW.producto_id 
          AND cantidad_disponible > 0 
          AND esta_agotado = FALSE
        ORDER BY fecha_creacion ASC; -- FIFO: primero en entrar, primero en salir

    DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = TRUE;

    -- Obtener stock actual
    SELECT stock INTO stock_actual FROM productos WHERE id = NEW.producto_id;

    -- Calcular costo promedio ponderado
    SELECT 
        COALESCE(SUM(cantidad_disponible * costo_unitario) / SUM(cantidad_disponible), 0)
    INTO costo_promedio
    FROM detalles_compras
    WHERE producto_id = NEW.producto_id 
      AND cantidad_disponible > 0;

    -- Actualizar el detalle de venta con el costo promedio
    UPDATE detalles_ventas 
    SET costo_unitario_promedio = costo_promedio,
        ganancia_unitaria = NEW.precio_unitario - costo_promedio,
        ganancia_total = NEW.cantidad * (NEW.precio_unitario - costo_promedio),
        porcentaje_ganancia_real = CASE 
            WHEN costo_promedio > 0 THEN ((NEW.precio_unitario - costo_promedio) / costo_promedio) * 100
            ELSE 0 
        END
    WHERE id = NEW.id;

    -- Procesar salidas FIFO
    OPEN cur_fifo;

    read_loop: LOOP
        FETCH cur_fifo INTO lote_id, cantidad_lote, costo_lote;

        IF done OR cantidad_restante <= 0 THEN
            LEAVE read_loop;
        END IF;

        -- Determinar cuánto descontar de este lote
        SET cantidad_a_descontar = LEAST(cantidad_restante, cantidad_lote);

        -- Crear movimiento de salida
        INSERT INTO movimientos_inventario (
            producto_id, tipo_movimiento, tipo_documento, documento_id, detalle_documento_id,
            cantidad, costo_unitario, costo_total, detalle_compra_origen_id,
            stock_anterior, stock_nuevo, fecha_movimiento
        ) VALUES (
            NEW.producto_id, 'Salida', 'Venta', NEW.venta_id, NEW.id,
            -cantidad_a_descontar, costo_lote, -(cantidad_a_descontar * costo_lote), lote_id,
            stock_actual, stock_actual - cantidad_a_descontar, NOW()
        );

        -- Actualizar cantidad disponible en el lote
        UPDATE detalles_compras 
        SET cantidad_disponible = cantidad_disponible - cantidad_a_descontar,
            esta_agotado = CASE WHEN (cantidad_disponible - cantidad_a_descontar) <= 0 THEN TRUE ELSE FALSE END,
            fecha_actualizacion = NOW()
        WHERE id = lote_id;

        -- Reducir cantidad restante
        SET cantidad_restante = cantidad_restante - cantidad_a_descontar;
        SET stock_actual = stock_actual - cantidad_a_descontar;

    END LOOP;

    CLOSE cur_fifo;

    -- Actualizar stock del producto
    UPDATE productos 
    SET stock = stock - NEW.cantidad,
        fecha_actualizacion = NOW()
    WHERE id = NEW.producto_id;
END$$

USE `weber`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `weber`.`tr_devoluciones_validar_detalle_antes_insertar`
BEFORE INSERT ON `weber`.`devoluciones`
FOR EACH ROW
BEGIN
    IF NEW.tipo_devolucion = 'Venta' THEN
        IF NEW.detalle_venta_id IS NULL OR NEW.detalle_compra_id IS NOT NULL THEN
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Para devoluciones de Venta, detalle_venta_id debe tener valor y detalle_compra_id debe ser NULL';
        END IF;
    ELSEIF NEW.tipo_devolucion = 'Compra' THEN
        IF NEW.detalle_compra_id IS NULL OR NEW.detalle_venta_id IS NOT NULL THEN
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Para devoluciones de Compra, detalle_compra_id debe tener valor y detalle_venta_id debe ser NULL';
        END IF;
    END IF;
END$$

USE `weber`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `weber`.`tr_devoluciones_validar_detalle_antes_actualizar`
BEFORE UPDATE ON `weber`.`devoluciones`
FOR EACH ROW
BEGIN
    IF NEW.tipo_devolucion = 'Venta' THEN
        IF NEW.detalle_venta_id IS NULL OR NEW.detalle_compra_id IS NOT NULL THEN
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Para devoluciones de Venta, detalle_venta_id debe tener valor y detalle_compra_id debe ser NULL';
        END IF;
    ELSEIF NEW.tipo_devolucion = 'Compra' THEN
        IF NEW.detalle_compra_id IS NULL OR NEW.detalle_venta_id IS NOT NULL THEN
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Para devoluciones de Compra, detalle_compra_id debe tener valor y detalle_venta_id debe ser NULL';
        END IF;
    END IF;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
