-- MySQL Script generated by MySQL Workbench
-- Thu Jul 24 09:47:01 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema weber
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema weber
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `weber` DEFAULT CHARACTER SET utf8mb3 ;
USE `weber` ;

-- -----------------------------------------------------
-- Table `weber`.`archivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`archivos` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` CHAR(36) NOT NULL COMMENT 'UUID único para el archivo',
  `model` VARCHAR(60) NOT NULL COMMENT 'Nombre del modelo',
  `model_id` BIGINT UNSIGNED NOT NULL,
  `nombre_original` VARCHAR(255) NOT NULL,
  `nombre_archivo` VARCHAR(255) NOT NULL COMMENT 'Nombre en el storage',
  `ruta_archivo` VARCHAR(500) NOT NULL,
  `extension` VARCHAR(10) NOT NULL,
  `tipo_archivo` ENUM('imagen', 'documento', 'video', 'audio', 'archivo', 'otro') NOT NULL,
  `etiquetas` JSON NULL DEFAULT NULL,
  `metadatos` JSON NULL DEFAULT NULL COMMENT 'EXIF, propiedades adicionales',
  `estado` ENUM('activo', 'archivado', 'eliminado', 'procesando') NOT NULL DEFAULT 'activo',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `archivos_uuid_unique` (`uuid` ASC) VISIBLE,
  INDEX `archivos_model_idx` (`model` ASC, `model_id` ASC) VISIBLE,
  INDEX `archivos_tipo_estado_idx` (`tipo_archivo` ASC, `estado` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Sistema de archivos completo y optimizado'
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `weber`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`categorias` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `categoria_padre_id` BIGINT UNSIGNED NULL DEFAULT NULL COMMENT 'Para categorías jerárquicas',
  `estado` ENUM('Activo', 'Inactivo') NOT NULL DEFAULT 'Activo',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `categorias_nombre_padre_unique` (`nombre` ASC, `categoria_padre_id` ASC) VISIBLE,
  INDEX `categorias_padre_idx` (`categoria_padre_id` ASC) VISIBLE,
  INDEX `categorias_estado_idx` (`estado` ASC) VISIBLE,
  CONSTRAINT `categorias_padre_foreign`
    FOREIGN KEY (`categoria_padre_id`)
    REFERENCES `weber`.`categorias` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Categorías jerárquicas de productos'
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `weber`.`departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`departamentos` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NOT NULL COMMENT 'Nombre del departamento (máx real: Archipiélago de San Andrés)',
  `codigo_dane` INT UNSIGNED NOT NULL COMMENT 'Código DANE del departamento',
  `region` ENUM('Caribe', 'Centro Oriente', 'Centro Sur', 'Eje Cafetero - Antioquia', 'Llano', 'Pacífico') NOT NULL,
  `estado` ENUM('Activo', 'Inactivo') NOT NULL DEFAULT 'Activo',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `departamentos_nombre_unique` (`nombre` ASC) VISIBLE,
  UNIQUE INDEX `departamentos_codigo_dane_unique` (`codigo_dane` ASC) VISIBLE,
  INDEX `departamentos_region_estado_idx` (`region` ASC, `estado` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 100
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Departamentos de Colombia con códigos DANE'
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `weber`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`productos` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(50) NULL DEFAULT NULL COMMENT 'SKU único del producto',
  `nombre` VARCHAR(150) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `stock` DECIMAL UNSIGNED NOT NULL DEFAULT '0',
  `stock_minimo` DECIMAL UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Stock mínimo para alertas',
  `stock_maximo` DECIMAL UNSIGNED NULL DEFAULT NULL COMMENT 'Stock máximo',
  `ganancia_sugerida` DECIMAL(5,2) UNSIGNED NOT NULL DEFAULT '50.00' COMMENT 'Porcentaje de ganancia sugerida',
  `precio_sugerido` DECIMAL(15,2) UNSIGNED NULL DEFAULT NULL COMMENT 'Precio de venta sugerido',
  `categoria_id` BIGINT(19) UNSIGNED NULL DEFAULT NULL COMMENT 'Categoría principal del producto',
  `atributos` JSON NULL DEFAULT NULL COMMENT 'Color, talla, marca, etc. (flexibles)',
  `estado` ENUM('Activo', 'Inactivo', 'Descontinuado', 'Agotado') NOT NULL DEFAULT 'Activo',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `productos_codigo_unique` (`codigo` ASC) VISIBLE,
  INDEX `productos_nombre_idx` (`nombre` ASC) VISIBLE,
  INDEX `productos_categoria_idx` (`categoria_id` ASC) VISIBLE,
  INDEX `productos_estado_stock_idx` (`estado` ASC, `stock` ASC) VISIBLE,
  INDEX `productos_ganancia_idx` (`ganancia_sugerida` ASC) VISIBLE,
  INDEX `productos_alertas_idx` (`stock` ASC, `stock_minimo` ASC) VISIBLE,
  FULLTEXT INDEX `productos_busqueda_fulltext` (`nombre`, `descripcion`) VISIBLE,
  CONSTRAINT `productos_categoria_foreign`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `weber`.`categorias` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Productos del sistema con atributos flexibles'
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `weber`.`municipios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`municipios` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(400) NOT NULL COMMENT 'Nombre del municipio',
  `departamento_id` BIGINT UNSIGNED NOT NULL,
  `codigo_dane` INT UNSIGNED NOT NULL COMMENT 'Código DANE completo del municipio',
  `abreviatura` VARCHAR(10) NULL DEFAULT NULL,
  `estado` ENUM('Activo', 'Inactivo') NOT NULL DEFAULT 'Activo',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `municipios_codigo_dane_unique` (`codigo_dane` ASC) VISIBLE,
  INDEX `municipios_departamento_nombre_idx` (`departamento_id` ASC, `nombre` ASC) VISIBLE,
  INDEX `municipios_estado_idx` (`estado` ASC) VISIBLE,
  CONSTRAINT `municipios_departamento_id_foreign`
    FOREIGN KEY (`departamento_id`)
    REFERENCES `weber`.`departamentos` (`id`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 99774
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Municipios de Colombia con códigos DANE'
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `weber`.`empresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`empresas` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NOT NULL COMMENT 'Razón social completa',
  `nit` BIGINT UNSIGNED NOT NULL COMMENT 'NIT sin puntos ni guiones (máx 10 dígitos + DV)',
  `email` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Email corporativo',
  `tipo_empresa` ENUM('Persona Natural', 'SAS', 'LTDA', 'SA', 'Cooperativa', 'Fundación', 'Otro') NOT NULL DEFAULT 'SAS',
  `estado` ENUM('Activo', 'Inactivo', 'Suspendido') NOT NULL DEFAULT 'Activo',
  `metadatos` JSON NULL DEFAULT NULL COMMENT 'Información adicional flexible',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `empresas_nit_unique` (`nit` ASC) VISIBLE,
  UNIQUE INDEX `empresas_email_unique` (`email` ASC) VISIBLE,
  INDEX `empresas_nombre_idx` (`nombre` ASC) VISIBLE,
  INDEX `empresas_estado_tipo_idx` (`estado` ASC, `tipo_empresa` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Empresas del sistema'
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `weber`.`sucursales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`sucursales` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `empresa_id` BIGINT UNSIGNED NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `administrador_id` BIGINT UNSIGNED NULL DEFAULT NULL COMMENT 'Referencia a perfiles_usuario',
  `direccion` VARCHAR(300) NOT NULL COMMENT 'Dirección completa',
  `municipio_id` BIGINT UNSIGNED NOT NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `tipo` ENUM('Principal', 'Subsede', 'Punto de Venta', 'Bodega') NOT NULL DEFAULT 'Principal',
  `estado` ENUM('Activo', 'Inactivo', 'Mantenimiento') NOT NULL DEFAULT 'Activo',
  `configuracion` JSON NULL DEFAULT NULL COMMENT 'Configuraciones específicas de la sucursal',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `sucursales_empresa_codigo_unique` (`empresa_id` ASC) VISIBLE,
  UNIQUE INDEX `sucursales_email_unique` (`email` ASC) VISIBLE,
  INDEX `sucursales_administrador_idx` (`administrador_id` ASC) VISIBLE,
  INDEX `sucursales_municipio_idx` (`municipio_id` ASC) VISIBLE,
  INDEX `sucursales_empresa_estado_idx` (`empresa_id` ASC, `estado` ASC) VISIBLE,
  INDEX `sucursales_tipo_estado_idx` (`tipo` ASC, `estado` ASC) VISIBLE,
  CONSTRAINT `sucursales_administrador_foreign`
    FOREIGN KEY (`administrador_id`)
    REFERENCES `weber`.`perfiles_usuario` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `sucursales_empresa_foreign`
    FOREIGN KEY (`empresa_id`)
    REFERENCES `weber`.`empresas` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `sucursales_municipio_foreign`
    FOREIGN KEY (`municipio_id`)
    REFERENCES `weber`.`municipios` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Sucursales por empresa'
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `weber`.`perfiles_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`perfiles_usuario` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `usuario_id` BIGINT UNSIGNED NOT NULL COMMENT 'ID del usuario en la tabla del framework',
  `codigo_empleado` VARCHAR(20) NULL DEFAULT NULL COMMENT 'Código de empleado interno',
  `tipo_documento` ENUM('CC', 'CE', 'TI', 'RC', 'PAS', 'NIT', 'PPT') NOT NULL,
  `documento` VARCHAR(15) NOT NULL COMMENT 'Número de documento sin puntos ni guiones',
  `nombres` VARCHAR(80) NOT NULL COMMENT 'Nombres completos',
  `apellidos` VARCHAR(80) NOT NULL COMMENT 'Apellidos completos',
  `telefono` VARCHAR(15) NULL DEFAULT NULL COMMENT 'Teléfono celular o fijo',
  `email_corporativo` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Email corporativo adicional',
  `direccion` VARCHAR(300) NULL DEFAULT NULL,
  `municipio_id` BIGINT UNSIGNED NULL,
  `fecha_nacimiento` DATE NULL DEFAULT NULL,
  `genero` ENUM('Masculino', 'Femenino', 'Otro', 'No especifica') NULL DEFAULT 'No especifica' COMMENT 'Género del usuario',
  `rol_negocio` ENUM('SuperAdmin', 'Administrador', 'Empleado', 'Cliente', 'Proveedor') NOT NULL,
  `fecha_contratacion` DATE NULL DEFAULT NULL COMMENT 'Para empleados',
  `fecha_terminacion` DATE NULL DEFAULT NULL COMMENT 'Para empleados',
  `salario` DECIMAL(12,2) UNSIGNED NULL DEFAULT NULL COMMENT 'Para empleados',
  `sucursal_id` BIGINT UNSIGNED NULL DEFAULT NULL COMMENT 'Sucursal de trabajo',
  `estado` ENUM('Activo', 'Inactivo', 'Suspendido', 'Bloqueado') NOT NULL DEFAULT 'Activo',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `perfiles_documento_unique` (`documento` ASC) VISIBLE,
  UNIQUE INDEX `perfiles_usuario_framework_unique` (`usuario_id` ASC) VISIBLE,
  UNIQUE INDEX `perfiles_email_corporativo_unique` (`email_corporativo` ASC) VISIBLE,
  UNIQUE INDEX `perfiles_codigo_empleado_unique` (`codigo_empleado` ASC) VISIBLE,
  INDEX `perfiles_municipio_idx` (`municipio_id` ASC) VISIBLE,
  INDEX `perfiles_sucursal_idx` (`sucursal_id` ASC) VISIBLE,
  INDEX `perfiles_rol_estado_idx` (`rol_negocio` ASC, `estado` ASC) VISIBLE,
  INDEX `perfiles_nombres_apellidos_idx` (`nombres` ASC, `apellidos` ASC) VISIBLE,
  INDEX `perfiles_tipo_documento_idx` (`tipo_documento` ASC, `documento` ASC) VISIBLE,
  CONSTRAINT `perfiles_municipio_foreign`
    FOREIGN KEY (`municipio_id`)
    REFERENCES `weber`.`municipios` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `perfiles_sucursal_foreign`
    FOREIGN KEY (`sucursal_id`)
    REFERENCES `weber`.`sucursales` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Perfiles de usuario del negocio'
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `weber`.`transacciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`transacciones` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `numero_factura` VARCHAR(80) NOT NULL,
  `sucursal_id` BIGINT(19) UNSIGNED NOT NULL COMMENT 'CRÍTICO: Sucursal donde se realiza la transacción',
  `perfil_proveedor_id` BIGINT(19) UNSIGNED NULL DEFAULT NULL COMMENT 'Cliente/Proveedor',
  `perfil_cliente_id` BIGINT UNSIGNED NULL,
  `perfil_empleado_id` BIGINT UNSIGNED NOT NULL COMMENT 'Empleado que registra',
  `fecha` DATETIME NOT NULL,
  `valor_base` DECIMAL(15,2) UNSIGNED NOT NULL DEFAULT '0.00',
  `descuento` DECIMAL(15,2) UNSIGNED NOT NULL DEFAULT '0.00',
  `total` DECIMAL(15,2) NOT NULL DEFAULT '0.00',
  `metodo_pago` ENUM('Efectivo', 'Tarjeta_Debito', 'Tarjeta_Credito', 'Transferencia', 'Credito', 'Mixto') NOT NULL,
  `estado` ENUM('Borrador', 'En_Proceso', 'Finalizada', 'Cancelada', 'Anulada') NOT NULL DEFAULT 'Borrador',
  `tipo_transaccion` ENUM('Venta', 'Compra') NOT NULL,
  `observaciones` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `transacciones_numero_sucursal_unique` (`sucursal_id` ASC, `numero_factura` ASC) VISIBLE,
  INDEX `transacciones_sucursal_fecha_idx` (`sucursal_id` ASC, `fecha` ASC) VISIBLE,
  INDEX `transacciones_perfil_proveedor_idx` (`perfil_proveedor_id` ASC) INVISIBLE,
  INDEX `transacciones_perfil_empleado_idx` (`perfil_empleado_id` ASC) VISIBLE,
  INDEX `transacciones_estado_tipo_idx` (`estado` ASC, `tipo_transaccion` ASC) VISIBLE,
  INDEX `transacciones_perfil_cliente_idx` (`perfil_cliente_id` ASC) VISIBLE,
  CONSTRAINT `transacciones_perfil_cliente_foreign`
    FOREIGN KEY (`perfil_cliente_id`)
    REFERENCES `weber`.`perfiles_usuario` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `transacciones_perfil_empleado_foreign`
    FOREIGN KEY (`perfil_empleado_id`)
    REFERENCES `weber`.`perfiles_usuario` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `transacciones_perfil_proveedor_foreign`
    FOREIGN KEY (`perfil_proveedor_id`)
    REFERENCES `weber`.`perfiles_usuario` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `transacciones_sucursal_foreign`
    FOREIGN KEY (`sucursal_id`)
    REFERENCES `weber`.`sucursales` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Transacciones base (compras y ventas) por sucursal'
ROW_FORMAT = COMPRESSED;


-- -----------------------------------------------------
-- Table `weber`.`detalles_transaccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`detalles_transaccion` (
  `id` BIGINT(19) UNSIGNED NOT NULL AUTO_INCREMENT,
  `transaccion_id` BIGINT(19) UNSIGNED NOT NULL,
  `producto_id` BIGINT(19) UNSIGNED NOT NULL,
  `lote` VARCHAR(50) NULL DEFAULT NULL,
  `fecha_vencimiento` DATE NULL DEFAULT NULL,
  `fecha_fabricacion` DATE NULL DEFAULT NULL,
  `cantidad` DECIMAL(10,3) UNSIGNED NOT NULL COMMENT 'Permite hasta 3 decimales',
  `costo_unitario` DECIMAL(15,4) UNSIGNED NOT NULL COMMENT 'Costo con 4 decimales de precisión',
  `total` DECIMAL(15,2) UNSIGNED NOT NULL,
  `cantidad_disponible` DECIMAL(10,3) UNSIGNED NOT NULL COMMENT 'Para control FIFO',
  `porcentaje_ganancia_aplicado` DECIMAL(5,2) UNSIGNED NOT NULL,
  `precio_venta_calculado` DECIMAL(15,2) UNSIGNED NOT NULL,
  `esta_agotado` TINYINT(1) NOT NULL DEFAULT '0',
  `observaciones` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `detalles_transaccion_transaccion_idx` (`transaccion_id` ASC) VISIBLE,
  INDEX `detalles_transaccion_producto_idx` (`producto_id` ASC) VISIBLE,
  INDEX `detalles_transaccion_lote_idx` (`lote` ASC) VISIBLE,
  INDEX `detalles_transaccion_vencimiento_idx` (`fecha_vencimiento` ASC) VISIBLE,
  INDEX `detalles_transaccion_fifo_idx` (`producto_id` ASC, `cantidad_disponible` ASC, `fecha_vencimiento` ASC) VISIBLE,
  INDEX `detalles_transaccion_agotado_idx` (`esta_agotado` ASC) VISIBLE,
  CONSTRAINT `detalles_transaccion_producto_foreign`
    FOREIGN KEY (`producto_id`)
    REFERENCES `weber`.`productos` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `detalles_transaccion_transaccion_foreign`
    FOREIGN KEY (`transaccion_id`)
    REFERENCES `weber`.`transacciones` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Detalles de transacciones con control FIFO'
ROW_FORMAT = COMPRESSED;


-- -----------------------------------------------------
-- Table `weber`.`devoluciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`devoluciones` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `sucursal_id` BIGINT(19) UNSIGNED NOT NULL,
  `numero` VARCHAR(50) NOT NULL COMMENT 'Número consecutivo de devolución',
  `fecha` DATETIME NOT NULL,
  `motivo` ENUM('Producto_Defectuoso', 'Error_Cantidad', 'Error_Producto', 'Cliente_No_Satisfecho', 'Vencimiento', 'Otro') NOT NULL,
  `detalle_transaccion_id` BIGINT(19) UNSIGNED NOT NULL COMMENT 'Detalle de la transacción original',
  `tipo_devolucion` ENUM('Venta', 'Compra') NOT NULL,
  `cantidad_devuelta` DECIMAL(10,3) UNSIGNED NOT NULL,
  `monto_devolucion` DECIMAL(15,2) UNSIGNED NOT NULL,
  `estado` ENUM('Pendiente', 'Procesada', 'Cancelada', 'Rechazada') NOT NULL DEFAULT 'Pendiente',
  `observaciones` TEXT NOT NULL,
  `perfil_empleado_id` BIGINT UNSIGNED NOT NULL COMMENT 'Empleado que procesa',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `devoluciones_numero_sucursal_unique` (`numero` ASC, `sucursal_id` ASC) VISIBLE,
  INDEX `devoluciones_sucursal_fecha_idx` (`sucursal_id` ASC, `fecha` ASC) VISIBLE,
  INDEX `devoluciones_tipo_estado_idx` (`tipo_devolucion` ASC, `estado` ASC) VISIBLE,
  INDEX `devoluciones_empleado_idx` (`perfil_empleado_id` ASC) VISIBLE,
  INDEX `devoluciones_detalle_transaccion_idx` (`detalle_transaccion_id` ASC) VISIBLE,
  CONSTRAINT `devoluciones_detalle_transaccion_foreign`
    FOREIGN KEY (`detalle_transaccion_id`)
    REFERENCES `weber`.`detalles_transaccion` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `devoluciones_empleado_foreign`
    FOREIGN KEY (`perfil_empleado_id`)
    REFERENCES `weber`.`perfiles_usuario` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `devoluciones_sucursal_foreign`
    FOREIGN KEY (`sucursal_id`)
    REFERENCES `weber`.`sucursales` (`id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Devoluciones de productos por sucursal'
ROW_FORMAT = COMPRESSED;


-- -----------------------------------------------------
-- Table `weber`.`producto_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`producto_categoria` (
  `producto_id` BIGINT UNSIGNED NOT NULL,
  `categoria_id` BIGINT UNSIGNED NOT NULL,
  `es_principal` TINYINT(1) NOT NULL DEFAULT '0' COMMENT 'Si es la categoría principal',
  `orden` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0' COMMENT 'Orden de importancia',
  PRIMARY KEY (`producto_id`, `categoria_id`),
  UNIQUE INDEX `producto_categoria_principal_unique` (`producto_id` ASC, `es_principal` ASC) VISIBLE,
  INDEX `producto_categoria_categoria_idx` (`categoria_id` ASC) VISIBLE,
  INDEX `producto_categoria_principal_idx` (`es_principal` ASC) VISIBLE,
  CONSTRAINT `producto_categoria_categoria_foreign`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `weber`.`categorias` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Relación productos-categorías con categoría principal'
ROW_FORMAT = DYNAMIC;

USE `weber` ;

-- -----------------------------------------------------
-- Placeholder table for view `weber`.`v_disponibilidad_fifo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`v_disponibilidad_fifo` (`producto_id` INT, `codigo` INT, `nombre_producto` INT, `sucursal_id` INT, `nombre_sucursal` INT, `detalle_transaccion_id` INT, `transaccion_id` INT, `cantidad_disponible` INT, `costo_unitario` INT, `precio_venta_calculado` INT, `porcentaje_ganancia_aplicado` INT, `lote` INT, `fecha_vencimiento` INT, `fecha_entrada` INT, `dias_para_vencer` INT, `estado_vencimiento` INT);

-- -----------------------------------------------------
-- Placeholder table for view `weber`.`v_inventario_sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`v_inventario_sucursal` (`sucursal_id` INT, `nombre_sucursal` INT, `producto_id` INT, `codigo` INT, `nombre_producto` INT, `stock_minimo` INT, `stock_maximo` INT, `stock_actual` INT, `estado_stock` INT, `lotes_disponibles` INT);

-- -----------------------------------------------------
-- Placeholder table for view `weber`.`v_rentabilidad_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`v_rentabilidad_productos` (`producto_id` INT, `codigo` INT, `nombre_producto` INT, `sucursal_id` INT, `nombre_sucursal` INT, `total_ventas` INT, `cantidad_total_vendida` INT, `ingresos_totales` INT, `costos_totales` INT, `ganancia_total` INT, `porcentaje_ganancia_promedio` INT, `porcentaje_ganancia_minimo` INT, `porcentaje_ganancia_maximo` INT);

-- -----------------------------------------------------
-- Placeholder table for view `weber`.`v_todas_transacciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weber`.`v_todas_transacciones` (`id` INT, `numero_factura` INT, `sucursal_id` INT, `nombre_sucursal` INT, `perfil_usuario_relacionado_id` INT, `perfil_empleado_id` INT, `fecha` INT, `monto` INT, `estado` INT, `tipo_transaccion` INT, `metodo_pago` INT, `observaciones` INT, `nombre_usuario_relacionado` INT, `nombre_empleado` INT);

-- -----------------------------------------------------
-- View `weber`.`v_disponibilidad_fifo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weber`.`v_disponibilidad_fifo`;
USE `weber`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `weber`.`v_disponibilidad_fifo` AS select `p`.`id` AS `producto_id`,`p`.`codigo` AS `codigo`,`p`.`nombre` AS `nombre_producto`,`t`.`sucursal_id` AS `sucursal_id`,`s`.`nombre` AS `nombre_sucursal`,`dt`.`id` AS `detalle_transaccion_id`,`t`.`id` AS `transaccion_id`,`dt`.`cantidad_disponible` AS `cantidad_disponible`,`dt`.`costo_unitario` AS `costo_unitario`,`dt`.`precio_venta_calculado` AS `precio_venta_calculado`,`dt`.`porcentaje_ganancia_aplicado` AS `porcentaje_ganancia_aplicado`,`dt`.`lote` AS `lote`,`dt`.`fecha_vencimiento` AS `fecha_vencimiento`,`t`.`fecha` AS `fecha_entrada`,(case when (`dt`.`fecha_vencimiento` is not null) then (to_days(`dt`.`fecha_vencimiento`) - to_days(curdate())) else NULL end) AS `dias_para_vencer`,(case when ((`dt`.`fecha_vencimiento` is not null) and ((to_days(`dt`.`fecha_vencimiento`) - to_days(curdate())) <= 30)) then 'Próximo a vencer' when ((`dt`.`fecha_vencimiento` is not null) and ((to_days(`dt`.`fecha_vencimiento`) - to_days(curdate())) <= 0)) then 'Vencido' else 'Normal' end) AS `estado_vencimiento` from (((`weber`.`productos` `p` join `weber`.`detalles_transaccion` `dt` on((`p`.`id` = `dt`.`producto_id`))) join `weber`.`transacciones` `t` on((`dt`.`transaccion_id` = `t`.`id`))) join `weber`.`sucursales` `s` on((`t`.`sucursal_id` = `s`.`id`))) where ((`dt`.`cantidad_disponible` > 0) and (`dt`.`esta_agotado` = false) and (`p`.`estado` = 'Activo') and (`s`.`estado` = 'Activo') and (`t`.`tipo_transaccion` = 'Compra')) order by `t`.`sucursal_id`,`p`.`id`,`t`.`fecha`;

-- -----------------------------------------------------
-- View `weber`.`v_inventario_sucursal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weber`.`v_inventario_sucursal`;
USE `weber`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `weber`.`v_inventario_sucursal` AS select `s`.`id` AS `sucursal_id`,`s`.`nombre` AS `nombre_sucursal`,`p`.`id` AS `producto_id`,`p`.`codigo` AS `codigo`,`p`.`nombre` AS `nombre_producto`,`p`.`stock_minimo` AS `stock_minimo`,`p`.`stock_maximo` AS `stock_maximo`,coalesce(sum((case when (`t`.`tipo_transaccion` = 'Compra') then `dt`.`cantidad_disponible` else 0 end)),0) AS `stock_actual`,(case when (coalesce(sum((case when (`t`.`tipo_transaccion` = 'Compra') then `dt`.`cantidad_disponible` else 0 end)),0) <= `p`.`stock_minimo`) then 'Stock Bajo' when (coalesce(sum((case when (`t`.`tipo_transaccion` = 'Compra') then `dt`.`cantidad_disponible` else 0 end)),0) = 0) then 'Agotado' else 'Normal' end) AS `estado_stock`,count(distinct (case when ((`t`.`tipo_transaccion` = 'Compra') and (`dt`.`cantidad_disponible` > 0)) then `dt`.`lote` end)) AS `lotes_disponibles` from (((`weber`.`sucursales` `s` join `weber`.`productos` `p`) left join `weber`.`transacciones` `t` on((`s`.`id` = `t`.`sucursal_id`))) left join `weber`.`detalles_transaccion` `dt` on(((`t`.`id` = `dt`.`transaccion_id`) and (`p`.`id` = `dt`.`producto_id`)))) where ((`s`.`estado` = 'Activo') and (`p`.`estado` = 'Activo')) group by `s`.`id`,`s`.`nombre`,`p`.`id`,`p`.`codigo`,`p`.`nombre`,`p`.`stock_minimo`,`p`.`stock_maximo` order by `s`.`nombre`,`p`.`nombre`;

-- -----------------------------------------------------
-- View `weber`.`v_rentabilidad_productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weber`.`v_rentabilidad_productos`;
USE `weber`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `weber`.`v_rentabilidad_productos` AS select `p`.`id` AS `producto_id`,`p`.`codigo` AS `codigo`,`p`.`nombre` AS `nombre_producto`,`t`.`sucursal_id` AS `sucursal_id`,`s`.`nombre` AS `nombre_sucursal`,count((case when (`t`.`tipo_transaccion` = 'Venta') then `dt`.`id` end)) AS `total_ventas`,coalesce(sum((case when (`t`.`tipo_transaccion` = 'Venta') then `dt`.`cantidad` else 0 end)),0) AS `cantidad_total_vendida`,coalesce(sum((case when (`t`.`tipo_transaccion` = 'Venta') then `dt`.`total` else 0 end)),0) AS `ingresos_totales`,coalesce(sum((case when (`t`.`tipo_transaccion` = 'Venta') then (`dt`.`cantidad` * `dt`.`costo_unitario`) else 0 end)),0) AS `costos_totales`,coalesce(sum((case when (`t`.`tipo_transaccion` = 'Venta') then (`dt`.`total` - (`dt`.`cantidad` * `dt`.`costo_unitario`)) else 0 end)),0) AS `ganancia_total`,coalesce(avg((case when (`t`.`tipo_transaccion` = 'Venta') then `dt`.`porcentaje_ganancia_aplicado` end)),0) AS `porcentaje_ganancia_promedio`,coalesce(min((case when (`t`.`tipo_transaccion` = 'Venta') then `dt`.`porcentaje_ganancia_aplicado` end)),0) AS `porcentaje_ganancia_minimo`,coalesce(max((case when (`t`.`tipo_transaccion` = 'Venta') then `dt`.`porcentaje_ganancia_aplicado` end)),0) AS `porcentaje_ganancia_maximo` from (((`weber`.`productos` `p` left join `weber`.`detalles_transaccion` `dt` on((`p`.`id` = `dt`.`producto_id`))) left join `weber`.`transacciones` `t` on((`dt`.`transaccion_id` = `t`.`id`))) left join `weber`.`sucursales` `s` on((`t`.`sucursal_id` = `s`.`id`))) where (`p`.`estado` = 'Activo') group by `p`.`id`,`p`.`codigo`,`p`.`nombre`,`t`.`sucursal_id`,`s`.`nombre`;

-- -----------------------------------------------------
-- View `weber`.`v_todas_transacciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weber`.`v_todas_transacciones`;
USE `weber`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `weber`.`v_todas_transacciones` AS select `t`.`id` AS `id`,`t`.`numero_factura` AS `numero_factura`,`t`.`sucursal_id` AS `sucursal_id`,`s`.`nombre` AS `nombre_sucursal`,(case when (`t`.`tipo_transaccion` = 'Venta') then `t`.`perfil_cliente_id` else `t`.`perfil_proveedor_id` end) AS `perfil_usuario_relacionado_id`,`t`.`perfil_empleado_id` AS `perfil_empleado_id`,`t`.`fecha` AS `fecha`,`t`.`total` AS `monto`,`t`.`estado` AS `estado`,`t`.`tipo_transaccion` AS `tipo_transaccion`,`t`.`metodo_pago` AS `metodo_pago`,`t`.`observaciones` AS `observaciones`,(case when (`t`.`tipo_transaccion` = 'Venta') then concat(`pc`.`nombres`,' ',`pc`.`apellidos`) else concat(`pp`.`nombres`,' ',`pp`.`apellidos`) end) AS `nombre_usuario_relacionado`,concat(`pe`.`nombres`,' ',`pe`.`apellidos`) AS `nombre_empleado` from ((((`weber`.`transacciones` `t` join `weber`.`sucursales` `s` on((`t`.`sucursal_id` = `s`.`id`))) join `weber`.`perfiles_usuario` `pe` on((`t`.`perfil_empleado_id` = `pe`.`id`))) left join `weber`.`perfiles_usuario` `pc` on((`t`.`perfil_cliente_id` = `pc`.`id`))) left join `weber`.`perfiles_usuario` `pp` on((`t`.`perfil_proveedor_id` = `pp`.`id`))) order by `t`.`fecha` desc;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
